// SPA effect names for native item/spell inspection.
    "HP",
    "AC",
    "Attack Power",
    "Movement Rate",
    "STR",
    "DEX",
    "AGI",
    "STA",
    "INT",
    "WIS",
    "CHA",
    "Haste",
    "Invisibility",
    "See Invis",
    "Enduring Breath",
    "Mana",
    "NPC Frenzy",
    "NPC Awareness",
    "NPC Aggro",
    "NPC Faction",
    "Blindness",
    "Stun",
    "Charm",
    "Fear",
    "Fatigue",
    "Bind Affinity",
    "Gate",
    "Dispel Magic",
    "Invis Vs Undead",
    "Invis Vs Animals",
    "NPC Aggro Radius",
    "Enthrall",
    "Create Item",
    "Summon Pet",
    "Confuse",
    "Disease",
    "Poison",
    "Detect Hostile",
    "Detect Magic",
    "No Twincast",
    "Invulnerability",
    "Banish",
    "Shadow Step",
    "Berserk",
    "Lycanthropy",
    "Vampirism",
    "Resist Fire",
    "Resist Cold",
    "Resist Poison",
    "Resist Disease",
    "Resist Magic",
    "Detect Traps",
    "Detect Undead",
    "Detect Summoned",
    "Detect Animals",
    "Stoneskin",
    "True North",
    "Levitation",
    "Change Form",
    "Damage Shield",
    "Transfer Item",
    "Item Lore",
    "Item Identify",
    "NPC Wipe Hate List",
    "Spin Stun",
    "Infravision",
    "Ultravision",
    "Eye Of Zomm",
    "Reclaim Energy",
    "Max HP",
    "Corpse Bomb",
    "Create Undead",
    "Preserve Corpse",
    "Bind Sight",
    "Feign Death",
    "Ventriloquism",
    "Sentinel",
    "Locate Corpse",
    "Spell Shield",
    "Instant HP",
    "Enchant Light",
    "Resurrect",
    "Summon Target",
    "Portal",
    "HP NPC Only",
    "Melee Proc",
    "NPC Help Radius",
    "Magnification",
    "Evacuate",
    "Height",
    "Ignore Pet",
    "Summon Corpse",
    "Hate",
    "Weather Control",
    "Fragile",
    "Sacrifice",
    "Silence",
    "Max Mana",
    "Bard Haste",
    "Root",
    "Heal Over Time",
    "Complete Heal",
    "Pet Fearless",
    "Call Pet",
    "Translocate",
    "NPC Anti Gate",
    "Beastlord Pet",
    "Alter Pet Level",
    "Familiar",
    "Create Item In Bag",
    "Archery",
    "Resist All",
    "Fizzle Skill",
    "Summon Mount",
    "Modify Hate",
    "Cornucopia",
    "Curse",
    "Hit Magic",
    "Amplification",
    "Attack Speed Max",
    "Healmod",
    "Ironmaiden",
    "Reduceskill",
    "Immunity",
    "Focus Damage Mod",
    "Focus Heal Mod",
    "Focus Resist Mod",
    "Focus Cast Time Mod",
    "Focus Duration Mod",
    "Focus Range Mod",
    "Focus Hate Mod",
    "Focus Reagent Mod",
    "Focus Manacost Mod",
    "Focus Stuntime Mod",
    "Focus Level Max",
    "Focus Resist Type",
    "Focus Target Type",
    "Focus Which SPA",
    "Focus Beneficial",
    "Focus Which Spell",
    "Focus Duration Min",
    "Focus Instant Only",
    "Focus Level Min",
    "Focus Casttime Min",
    "Focus Casttime Max",
    "NPC Portal Warder Banish",
    "Portal Locations",
    "Percent Heal",
    "Stacking Block",
    "Strip Virtual Slot",
    "Divine Intervention",
    "Pocket Pet",
    "Pet Swarm",
    "Health Balance",
    "Cancel Negative Magic",
    "Pop Resurrect",
    "Mirror",
    "Feedback",
    "Reflect",
    "Modify All Stats",
    "Change Sobriety",
    "Spell Guard",
    "Melee Guard",
    "Absorb Hit",
    "Object Sense Trap",
    "Object Disarm Trap",
    "Object Picklock",
    "Focus Pet",
    "Defensive",
    "Critical Melee",
    "Critical Spell",
    "Crippling Blow",
    "Evasion",
    "Riposte",
    "Dodge",
    "Parry",
    "Dual Wield",
    "Double Attack",
    "Melee Lifetap",
    "Puretone",
    "Sanctification",
    "Fearless",
    "Hundred Hands",
    "Skill Increase Chance",
    "Accuracy",
    "Skill Damage Mod",
    "Min Damage Done Mod",
    "Mana Balance",
    "Block",
    "Endurance",
    "Increase Max Endurance",
    "Amnesia",
    "Hate Over Time",
    "Skill Attack",
    "Fade",
    "Stun Resist",
    "Strikethrough1",
    "Skill Damage Taken",
    "Instant Endurance",
    "Taunt",
    "Proc Chance",
    "Range Ability",
    "Illusion Others",
    "Mass Group Buff",
    "Group Fear Immunity",
    "Rampage",
    "AE Taunt",
    "Flesh To Bone",
    "Purge Poison",
    "Cancel Beneficial",
    "Shield Caster",
    "Destructive Force",
    "Focus Frenzied Devastation",
    "Pet Percent Max HP",
    "HP Max HP",
    "Pet Percent Avoidance",
    "Melee Accuracy",
    "Headshot",
    "Pet Crit Melee",
    "Slay Undead",
    "Increase Skill Damage",
    "Reduce Weight",
    "Block Behind",
    "Double Riposte",
    "Add Riposte",
    "Give Double Attack",
    "2H Bash",
    "Reduce Skill Timer",
    "Acrobatics",
    "Cast Through Stun",
    "Extended Shielding",
    "Bash Chance",
    "Divine Save",
    "Metabolism",
    "Poison Mastery",
    "Focus Channeling",
    "Free Pet",
    "Pet Affinity",
    "Perm Illusion",
    "Stonewall",
    "String Unbreakable",
    "Improve Reclaim Energy",
    "Increase Change Memwipe",
    "Enhanced Charm",
    "Enhanced Root",
    "Trap Circumvention",
    "Increase Air Supply",
    "Increase Max Skill",
    "Extra Specialization",
    "Offhand Min Weapon Damage",
    "Increase Proc Chance",
    "Endless Quiver",
    "Backstab Front",
    "Chaotic Stab",
    "No Effect",
    "Shielding Duration Mod",
    "Shroud Of Stealth",
    "Give Pet Hold",
    "Triple Backstab",
    "AC Limit Mod",
    "Add Instrument Mod",
    "Song Mod Cap",
    "Increase Stat Cap",
    "Tradeskill Mastery",
    "Reduce AA Timer",
    "No Fizzle",
    "Add 2H Attack Chance",
    "Add Pet Commands",
    "Alchemy Fail Rate",
    "First Aid",
    "Extend Song Range",
    "Base Run Mod",
    "Increase Casting Level",
    "DoT Crit",
    "Heal Crit",
    "Mend Crit",
    "Dual Wield Amount",
    "Extra Di Chance",
    "Finishing Blow",
    "Flurry",
    "Pet Flurry",
    "Pet Feign",
    "Increase Bandage Amount",
    "Wu Attack",
    "Improve LoH",
    "Nimble Evasion",
    "Focus Damage Amount",
    "Focus Duration Amount",
    "Add Proc Hit",
    "Doom Effect",
    "Increase Run Speed Cap",
    "Purify",
    "Strikethrough",
    "Stun Resist2",
    "Spell Crit Chance",
    "Reduce Special Timer",
    "Focus Damage Mod Detrimental",
    "Focus Damage Amount Detrimental",
    "Tiny Companion",
    "Wake Dead",
    "Doppelganger",
    "Increase Range Damage",
    "Focus Damage Mod Crit",
    "Focus Damage Amount Crit",
    "Secondary Riposte Mod",
    "Damage Shield Mod",
    "Weak Dead 2",
    "Appraisal",
    "Zone Suspend Minion",
    "Teleport Casters Bindpoint",
    "Focus Reuse Timer",
    "Focus Combat Skill",
    "Observer",
    "Forage Master",
    "Improved Invis",
    "Improved Invis Undead",
    "Improved Invis Animals",
    "Increase Worn HP Regen Cap",
    "Increase Worn Mana Regen Cap",
    "Critical HP Regen",
    "Shield Block Chance",
    "Reduce Target Hate",
    "Gate Starting City",
    "Defensive Proc",
    "HP For Mana",
    "No Break AE Sneak",
    "Add Spell Slots",
    "Add Buff Slots",
    "Increase Negative HP Limit",
    "Mana Absorb Percent Damage",
    "Crit Attack Modifier",
    "Fail Alchemy Item Recovery",
    "Summon To Corpse",
    "Doom Rune Effect",
    "No Move HP",
    "Focused Immunity",
    "Illusionary Target",
    "Increase Exp Mod",
    "Expedient Recovery",
    "Focus Casting Proc",
    "Chance Spell",
    "Worn Attack Cap",
    "No Panic",
    "Spell Interrupt",
    "Item Channeling",
    "Assassinate Max Level",
    "Headshot Max Level",
    "Double Ranged Attack",
    "Focus Mana Min",
    "Increase Shield Damage",
    "Manaburn",
    "Spawn Interactive Object",
    "Increase Trap Count",
    "Increase SOI Count",
    "Deactivate All Traps",
    "Learn Trap",
    "Change Trigger Type",
    "Focus Mute",
    "Instant Mana",
    "Passive Sense Trap",
    "Proc On Kill Shot",
    "Proc On Death",
    "Potion Belt",
    "Bandolier",
    "Add Triple Attack Chance",
    "Proc On Spell Kill Shot",
    "Group Shielding",
    "Modify Body Type",
    "Modify Faction",
    "Corruption",
    "Resist Corruption",
    "Slow",
    "Grant Foraging",
    "Doom Always",
    "Trigger Spell",
    "Crit Dot Damage Mod",
    "Fling",
    "Doom Entity",
    "Resist Other SPA",
    "Directional Teleport",
    "Explosive Knockback",
    "Fling Toward",
    "Suppression",
    "Focus Casting Proc Normalized",
    "Fling At",
    "Focus Which Group",
    "Doom Dispeller",
    "Doom Dispellee",
    "Summon All Corpses",
    "Refresh Spell Timer",
    "Lockout Spell Timer",
    "Focus Mana Max",
    "Focus Heal Amount",
    "Focus Heal Mod Beneficial",
    "Focus Heal Amount Beneficial",
    "Focus Heal Mod Crit",
    "Focus Heal Amount Crit",
    "Add Pet AC",
    "Focus Swarm Pet Duration",
    "Focus Twincast Chance",
    "Healburn",
    "Mana Ignite",
    "Endurance Ignite",
    "Focus Spell Class",
    "Focus Spell Subclass",
    "Staff Block Chance",
    "Doom Limit Use",
    "Doom Focus Used",
    "Limit HP",
    "Limit Mana",
    "Limit Endurance",
    "Focus Limit Class",
    "Focus Limit Race",
    "Focus Base Effects",
    "Focus Limit Skill",
    "Focus Limit Item Class",
    "Ac2",
    "Mana2",
    "Focus Increase Skill Damage 2",
    "Proc Effect 2",
    "Focus Limit Use",
    "Focus Limit Use Amount",
    "Focus Limit Use Min",
    "Focus Limit Use Type",
    "Gravitate",
    "Fly",
    "Add Extended Target Slots",
    "Skill Proc",
    "Proc Skill Modifier",
    "Skill Proc Success",
    "Post Effect",
    "Post Effect Data",
    "Expand Max Active Trophy Benefits",
    "Add Normalized Skill Min Damage Amount",
    "Add Normalized Skill Min Damage Amount 2",
    "Fragile Defense",
    "Freeze Buff Timer",
    "Teleport To Anchor",
    "Translocate To Anchor",
    "Assassinate",
    "Finishing Blow Max",
    "Distance Removal",
    "Require Target Doom",
    "Require Caster Doom",
    "Improved Taunt",
    "Add Merc Slot",
    "Stacker A",
    "Stacker B",
    "Stacker C",
    "Stacker D",
    "Dot Guard",
    "Melee Threshold Guard",
    "Spell Threshold Guard",
    "Melee Threshold Doom",
    "Spell Threshold Doom",
    "Add Hate Percent",
    "Add Hate Over Time Percent",
    "Resource Tap",
    "Faction Mod",
    "Skill Damage Mod 2",
    "Override Not Focusable",
    "Focus Damage Mod 2",
    "Focus Damage Amount 2",
    "Shield",
    "PC Pet Rampage",
    "PC Pet AE Rampage",
    "PC Pet Flurry",
    "Damage Shield Mitigation Amount",
    "Damage Shield Mitigation Percent",
    "Chance Best In Spell Group",
    "Trigger Best In Spell Group",
    "Double Melee Attacks",
    "AA Buy Next Rank",
    "Double Backstab Front",
    "Pet Melee Crit Damage Mod",
    "Trigger Spell Non Item",
    "Weapon Stance",
    "Hatelist To Top",
    "Hatelist To Tail",
    "Focus Limit Min Value",
    "Focus Limit Max Value",
    "Focus Cast Spell On Land",
    "Skill Base Damage Mod",
    "Focus Incoming Damage Mod",
    "Focus Incoming Damage Amount",
    "Focus Limit Caster Class",
    "Focus Limit Same Caster",
    "Extend Tradeskill Cap",
    "Defender Melee Force Percent",
    "Worn Endurance Regen Cap",
    "Focus Min Reuse Time",
    "Focus Max Reuse Time",
    "Focus Endurance Min",
    "Focus Endurance Max",
    "Pet Add Atk",
    "Focus Duration Max",
    "Crit Melee Damage Mod Max",
    "Focus Cast Proc No Bypass",
    "Add Extra Primary Attack Percent",
    "Add Extra Secondary Attack Percent",
    "Focus Cast Time Mod2",
    "Focus Cast Time Amount",
    "Fearstun",
    "Melee Damage Position Mod",
    "Melee Damage Position Amount",
    "Damage Taken Position Mod",
    "Damage Taken Position Amount",
    "Amplify Mod",
    "Amplify Amount",
    "Health Transfer",
    "Focus Resist Incoming",
    "Focus Timer Min",
    "Proc Timer Mod",
    "Mana Max",
    "Endurance Max",
    "AC Avoidance Max",
    "AC Mitigation Max",
    "Attack Offense Max",
    "Attack Accuracy Max",
    "Luck Amount",
    "Luck Percent",
    "Endurance Absorb Percent Damage",
    "Instant Mana Percent",
    "Instant Endurance Percent",
    "Duration HP Percent",
    "Duration Mana Percent",
    "Duration Endurance Percent",
