/*	EQEmu: EQEmulator

	Copyright (C) 2001-2026 EQEmu Development Team

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
#include "common/repositories/items_repository.h"
#include "common/rulesys.h"
#include "common/strings.h"
#include "zone/client.h"

#include <algorithm>
#include <ctime>
#include <limits>

namespace {
	void SendLiveItemUsage(Client *c)
	{
		c->Message(
			Chat::White,
			fmt::format(
				"Live Items: enabled [{}], range [{}-{}], poll [{}s].",
				RuleB(Items, LiveItemLoading) ? "true" : "false",
				RuleI(Items, LiveItemMinID),
				RuleI(Items, LiveItemMaxID),
				RuleI(Items, LiveItemPollIntervalSeconds)
			).c_str()
		);
		c->Message(Chat::White, "Usage: #liveitem status [item_id]");
		c->Message(Chat::White, "Usage: #liveitem clear [item_id|all]");
		c->Message(Chat::White, "Usage: #liveitem clone [new_item_id] [source_item_id]");
		c->Message(Chat::White, "Usage: #liveitem summon [item_id] [charges]");
		c->Message(Chat::White, "Usage: #liveitem bump [item_id] [hp] [mana] [damage]");
	}

	bool IsValidLiveItemID(Client *c, const uint32 item_id)
	{
		if (!item_id || item_id > static_cast<uint32>(std::numeric_limits<int32>::max())) {
			c->Message(Chat::White, "Enter an item ID from 1 to 2147483647.");
			return false;
		}

		return true;
	}

	void SendItemSummary(Client *c, const EQ::ItemData *item)
	{
		if (!item) {
			c->Message(Chat::White, "Resolved Item: not found.");
			return;
		}

		c->Message(
			Chat::White,
			fmt::format(
				"Resolved Item: [{}] {} | HP [{}] Mana [{}] Damage [{}] Delay [{}] Haste [{}] Proc [{}]",
				item->ID,
				item->Name,
				item->HP,
				item->Mana,
				item->Damage,
				item->Delay,
				item->Haste,
				item->Proc.Effect
			).c_str()
		);
	}

	void SummonLiveItem(Client *c, const uint32 item_id, int16 charges)
	{
		const auto *item = database.GetItem(item_id);
		if (!item) {
			c->Message(Chat::White, fmt::format("Item ID {} does not exist.", item_id).c_str());
			return;
		}

		if (item->MinStatus > c->Admin()) {
			c->Message(
				Chat::White,
				fmt::format(
					"Insufficient status to summon this item, current status is {}, required status is {}.",
					c->Admin(),
					item->MinStatus
				).c_str()
			);
			return;
		}

		c->SummonItem(item_id, charges);

		const auto *new_item = database.CreateItem(item_id, charges);
		EQ::SayLinkEngine linker;
		linker.SetLinkType(EQ::saylink::SayLinkItemInst);
		linker.SetItemInst(new_item);

		c->Message(Chat::White, fmt::format("You have summoned {}.", linker.GenerateLink()).c_str());
		safe_delete(new_item);
	}

	bool UpsertLiveItemClone(Client *c, const uint32 target_id, const uint32 source_id)
	{
		auto source = ItemsRepository::FindOne(database, source_id);
		if (!source.id) {
			c->Message(Chat::White, fmt::format("Source item ID {} does not exist.", source_id).c_str());
			return false;
		}

		const bool replacing = ItemsRepository::FindOne(database, target_id).id != 0;

		source.id        = target_id;
		source.minstatus = 0;
		source.Name      = fmt::format("Live Test Item {}", target_id);
		source.lore      = fmt::format("A live item cloned from {}", source_id);
		source.comment   = "Generated by #liveitem clone";
		source.hp += 25;
		source.mana += 25;
		source.haste = std::max(source.haste, 5);
		source.damage = std::max<int32>(source.damage + 1, 1);
		source.delay = std::max<int32>(source.delay, 20);
		source.updated = std::time(nullptr);

		if (replacing) {
			if (!ItemsRepository::UpdateOne(database, source)) {
				c->Message(Chat::White, fmt::format("Failed to update live item ID {}.", target_id).c_str());
				return false;
			}
		} else {
			ItemsRepository::InsertOne(database, source);
			if (!ItemsRepository::FindOne(database, target_id).id) {
				c->Message(Chat::White, fmt::format("Failed to insert live item ID {}.", target_id).c_str());
				return false;
			}
		}

		database.ClearLiveItemCache(target_id);
		c->Message(
			Chat::White,
			fmt::format(
				"{} live item ID {} from source item ID {}.",
				replacing ? "Updated" : "Created",
				target_id,
				source_id
			).c_str()
		);

		return true;
	}
}

void command_liveitem(Client *c, const Seperator *sep)
{
	const auto arguments = sep->argnum;
	if (!arguments || !strcasecmp(sep->arg[1], "help")) {
		SendLiveItemUsage(c);
		return;
	}

	const bool is_status = !strcasecmp(sep->arg[1], "status");
	const bool is_clear  = !strcasecmp(sep->arg[1], "clear");
	const bool is_clone  = !strcasecmp(sep->arg[1], "clone");
	const bool is_summon = !strcasecmp(sep->arg[1], "summon");
	const bool is_bump   = !strcasecmp(sep->arg[1], "bump");

	if (!is_status && !is_clear && !is_clone && !is_summon && !is_bump) {
		SendLiveItemUsage(c);
		return;
	}

	if (is_clear) {
		if (arguments < 2 || !strcasecmp(sep->arg[2], "all")) {
			database.ClearLiveItemCache();
			c->Message(Chat::White, "Cleared all live item cache entries.");
			return;
		}

		if (!sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		c->Message(
			Chat::White,
			fmt::format(
				"Live item cache entry for item ID {} {}.",
				item_id,
				database.ClearLiveItemCache(item_id) ? "cleared" : "was not cached"
			).c_str()
		);
		return;
	}

	if (is_status) {
		if (arguments < 2 || !sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		const bool eligible = database.IsLiveItemID(item_id);
		c->Message(Chat::White, fmt::format("Live Item ID [{}]: {}", item_id, eligible ? "eligible" : "not eligible").c_str());

		const auto *item = database.GetItem(item_id);
		SendItemSummary(c, item);

		SharedDatabase::LiveItemCacheEntry entry {};
		if (database.GetLiveItemCacheEntry(item_id, entry)) {
			c->Message(
				Chat::White,
				fmt::format(
					"Cache: exists [{}] last_checked [{}] updated [{}]",
					entry.exists ? "true" : "false",
					entry.last_checked,
					entry.updated
				).c_str()
			);
		} else {
			c->Message(Chat::White, "Cache: no entry.");
		}
		return;
	}

	if (is_clone) {
		if (arguments < 3 || !sep->IsNumber(2) || !sep->IsNumber(3)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto target_id = Strings::ToUnsignedInt(sep->arg[2]);
		const auto source_id = Strings::ToUnsignedInt(sep->arg[3]);
		if (!IsValidLiveItemID(c, target_id) || !IsValidLiveItemID(c, source_id)) {
			return;
		}

		if (!database.IsLiveItemID(target_id)) {
			c->Message(Chat::White, fmt::format("Item ID {} is outside the configured live item range.", target_id).c_str());
			return;
		}

		if (UpsertLiveItemClone(c, target_id, source_id)) {
			SummonLiveItem(c, target_id, 1);
		}
		return;
	}

	if (is_summon) {
		if (arguments < 2 || !sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		const int16 charges = (arguments >= 3 && sep->IsNumber(3)) ? static_cast<int16>(Strings::ToInt(sep->arg[3])) : -1;
		SummonLiveItem(c, item_id, charges);
		return;
	}

	if (is_bump) {
		if (arguments < 2 || !sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		if (!database.IsLiveItemID(item_id)) {
			c->Message(Chat::White, fmt::format("Item ID {} is outside the configured live item range.", item_id).c_str());
			return;
		}

		auto item = ItemsRepository::FindOne(database, item_id);
		if (!item.id) {
			c->Message(Chat::White, fmt::format("Item ID {} does not exist in the database.", item_id).c_str());
			return;
		}

		const int hp_step     = (arguments >= 3 && sep->IsNumber(3)) ? Strings::ToInt(sep->arg[3]) : 5;
		const int mana_step   = (arguments >= 4 && sep->IsNumber(4)) ? Strings::ToInt(sep->arg[4]) : 5;
		const int damage_step = (arguments >= 5 && sep->IsNumber(5)) ? Strings::ToInt(sep->arg[5]) : 1;

		item.hp = std::max(0, item.hp + hp_step);
		item.mana = std::max(0, item.mana + mana_step);
		item.damage = std::max(0, item.damage + damage_step);
		item.updated = std::time(nullptr);

		if (!ItemsRepository::UpdateOne(database, item)) {
			c->Message(Chat::White, fmt::format("Failed to bump item ID {}.", item_id).c_str());
			return;
		}

		c->Message(
			Chat::White,
			fmt::format(
				"Bumped item ID {} to HP [{}], Mana [{}], Damage [{}]. Wait up to the live item poll interval for held instances to refresh.",
				item_id,
				item.hp,
				item.mana,
				item.damage
			).c_str()
		);
	}
}
