/*	EQEmu: EQEmulator

	Copyright (C) 2001-2026 EQEmu Development Team

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
#include "common/repositories/items_repository.h"
#include "common/data_bucket.h"
#include "common/item_data.h"
#include "common/ipc_mutex.h"
#include "common/repositories/data_buckets_repository.h"
#include "common/rulesys.h"
#include "common/strings.h"
#include "zone/client.h"

#include <algorithm>
#include <array>
#include <cctype>
#include <cstring>
#include <ctime>
#include <initializer_list>
#include <limits>
#include <unordered_set>
#include <utility>
#include <vector>

namespace {
	bool LiveItemsEnabled()
	{
		return RuleB(CustomFeatures, LiveItemsEnabled);
	}

	void SendLiveItemUsage(Client *c)
	{
		c->Message(
			Chat::White,
			fmt::format(
				"Live Items: enabled [{}], range [{}-{}], poll [{}s].",
				RuleB(Items, LiveItemLoading) ? "true" : "false",
				RuleI(Items, LiveItemMinID),
				RuleI(Items, LiveItemMaxID),
				RuleI(Items, LiveItemPollIntervalSeconds)
			).c_str()
		);
		c->Message(Chat::White, "Usage: #liveitem status [item_id]");
		c->Message(Chat::White, "Usage: #liveitem clear [item_id|all]");
		c->Message(Chat::White, "Usage: #liveitem clone [new_item_id] [source_item_id]");
		c->Message(Chat::White, "Usage: #liveitem summon [item_id] [charges]");
		c->Message(Chat::White, "Usage: #liveitem bump [item_id] [hp] [mana] [damage]");
	}

	bool IsValidLiveItemID(Client *c, const uint32 item_id)
	{
		if (!item_id || item_id > static_cast<uint32>(std::numeric_limits<int32>::max())) {
			c->Message(Chat::White, "Enter an item ID from 1 to 2147483647.");
			return false;
		}

		return true;
	}

	void SendItemSummary(Client *c, const EQ::ItemData *item)
	{
		if (!item) {
			c->Message(Chat::White, "Resolved Item: not found.");
			return;
		}

		c->Message(
			Chat::White,
			fmt::format(
				"Resolved Item: [{}] {} | HP [{}] Mana [{}] Damage [{}] Delay [{}] Haste [{}] Proc [{}]",
				item->ID,
				item->Name,
				item->HP,
				item->Mana,
				item->Damage,
				item->Delay,
				item->Haste,
				item->Proc.Effect
			).c_str()
		);
	}

	void SummonLiveItem(Client *c, const uint32 item_id, int16 charges)
	{
		const auto *item = database.GetItem(item_id);
		if (!item) {
			c->Message(Chat::White, fmt::format("Item ID {} does not exist.", item_id).c_str());
			return;
		}

		if (item->MinStatus > c->Admin()) {
			c->Message(
				Chat::White,
				fmt::format(
					"Insufficient status to summon this item, current status is {}, required status is {}.",
					c->Admin(),
					item->MinStatus
				).c_str()
			);
			return;
		}

		c->SummonItem(item_id, charges);

		const auto *new_item = database.CreateItem(item_id, charges);
		EQ::SayLinkEngine linker;
		linker.SetLinkType(EQ::saylink::SayLinkItemInst);
		linker.SetItemInst(new_item);

		c->Message(Chat::White, fmt::format("You have summoned {}.", linker.GenerateLink()).c_str());
		safe_delete(new_item);
	}

	bool UpsertLiveItemClone(Client *c, const uint32 target_id, const uint32 source_id)
	{
		auto source = ItemsRepository::FindOne(database, source_id);
		if (!source.id) {
			c->Message(Chat::White, fmt::format("Source item ID {} does not exist.", source_id).c_str());
			return false;
		}

		const bool replacing = ItemsRepository::FindOne(database, target_id).id != 0;

		source.id        = target_id;
		source.minstatus = 0;
		source.Name      = fmt::format("Live Test Item {}", target_id);
		source.lore      = fmt::format("A live item cloned from {}", source_id);
		source.comment   = "Generated by #liveitem clone";
		source.hp += 25;
		source.mana += 25;
		source.haste = std::max(source.haste, 5);
		source.damage = std::max<int32>(source.damage + 1, 1);
		source.delay = std::max<int32>(source.delay, 20);
		source.updated = std::time(nullptr);

		if (replacing) {
			if (!ItemsRepository::UpdateOne(database, source)) {
				c->Message(Chat::White, fmt::format("Failed to update live item ID {}.", target_id).c_str());
				return false;
			}
		} else {
			ItemsRepository::InsertOne(database, source);
			if (!ItemsRepository::FindOne(database, target_id).id) {
				c->Message(Chat::White, fmt::format("Failed to insert live item ID {}.", target_id).c_str());
				return false;
			}
		}

		database.ClearLiveItemCache(target_id);
		c->Message(
			Chat::White,
			fmt::format(
				"{} live item ID {} from source item ID {}.",
				replacing ? "Updated" : "Created",
				target_id,
				source_id
			).c_str()
		);

		return true;
	}

	constexpr const char *LiveItemForgeNextBucket = "live_item_forge.next_item_id";
	constexpr const char *LiveItemForgeDraftBucketPrefix = "live_item_forge_draft_";

	struct ItemForgeDefinition {
		uint32 item_id = 0;
		std::string name = "Forged Item";
		std::string item_type = "weapon";
		int hp = 25;
		int mana = 25;
		int ac = 5;
		int damage = 5;
		int delay = 24;
		int haste = 0;
	};

	std::string TrimItemForgeText(std::string value)
	{
		while (!value.empty() && std::isspace(static_cast<unsigned char>(value.front()))) {
			value.erase(value.begin());
		}

		while (!value.empty() && std::isspace(static_cast<unsigned char>(value.back()))) {
			value.pop_back();
		}

		return value;
	}

	std::string DecodeItemForgeText(const std::string &value)
	{
		std::string decoded;
		decoded.reserve(std::min<size_t>(value.size(), 60));

		for (const auto raw_ch : value) {
			const auto ch = raw_ch == '_' ? ' ' : raw_ch;
			const bool alpha = (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z');
			const bool digit = ch >= '0' && ch <= '9';
			const bool separator = ch == ' ' || ch == '-' || ch == '\'';
			if (!alpha && !digit && !separator) {
				continue;
			}

			if (std::isspace(static_cast<unsigned char>(ch))) {
				if (decoded.empty() || decoded.back() == ' ') {
					continue;
				}

				decoded.push_back(' ');
			} else {
				decoded.push_back(ch);
			}

			if (decoded.size() >= 60) {
				break;
			}
		}

		return TrimItemForgeText(decoded);
	}

	bool HasItemForgeNamedArgs(const Seperator *sep)
	{
		for (int index = 2; index <= sep->argnum; ++index) {
			if (std::strchr(sep->arg[index], '=')) {
				return true;
			}
		}

		return false;
	}

	std::string GetItemForgeNamedArg(const Seperator *sep, const std::string &key)
	{
		const auto wanted = Strings::ToLower(key);
		for (int index = 2; index <= sep->argnum; ++index) {
			const std::string token = sep->arg[index];
			const auto separator = token.find('=');
			if (separator == std::string::npos) {
				continue;
			}

			if (Strings::ToLower(token.substr(0, separator)) == wanted) {
				return token.substr(separator + 1);
			}
		}

		return {};
	}

	int GetItemForgeNamedInt(const Seperator *sep, const std::string &key, const int fallback)
	{
		const auto value = GetItemForgeNamedArg(sep, key);
		return value.empty() ? fallback : Strings::ToInt(value);
	}

	std::string SanitizeItemForgeName(const std::string &name)
	{
		auto decoded = DecodeItemForgeText(name);
		if (decoded.empty()) {
			return {};
		}

		for (auto &ch : decoded) {
			if (std::isspace(static_cast<unsigned char>(ch))) {
				ch = '_';
			}
		}

		return decoded;
	}

	std::string ItemForgeDraftBucketKey(Client *c)
	{
		return fmt::format("{}{}", LiveItemForgeDraftBucketPrefix, c->CharacterID());
	}

	bool ParseItemForgeToken(const std::string &token, std::string &key, std::string &value)
	{
		const auto separator = token.find('=');
		if (separator == std::string::npos) {
			return false;
		}

		key = Strings::ToLower(token.substr(0, separator));
		value = token.substr(separator + 1);
		return !key.empty() && !value.empty();
	}

	std::vector<std::pair<std::string, std::string>> ParseItemForgeDraft(const std::string &draft)
	{
		std::vector<std::pair<std::string, std::string>> values;
		const auto tokens = Strings::Split(draft, ' ');
		for (const auto &token : tokens) {
			std::string key;
			std::string value;
			if (ParseItemForgeToken(token, key, value)) {
				values.emplace_back(key, value);
			}
		}

		return values;
	}

	std::string BuildItemForgeDraft(const std::vector<std::pair<std::string, std::string>> &values)
	{
		std::vector<std::string> tokens;
		tokens.reserve(values.size());
		for (const auto &[key, value] : values) {
			if (!key.empty() && !value.empty()) {
				tokens.emplace_back(fmt::format("{}={}", key, value));
			}
		}

		return Strings::Join(tokens, " ");
	}

	void SetItemForgeDraftValue(std::vector<std::pair<std::string, std::string>> &values, const std::string &key, const std::string &value)
	{
		for (auto &[existing_key, existing_value] : values) {
			if (existing_key == key) {
				existing_value = value;
				return;
			}
		}

		values.emplace_back(key, value);
	}

	std::string GetItemForgeDraftValue(const std::vector<std::pair<std::string, std::string>> &values, const std::string &key)
	{
		const auto wanted = Strings::ToLower(key);
		for (const auto &[existing_key, existing_value] : values) {
			if (existing_key == wanted) {
				return existing_value;
			}
		}

		return {};
	}

	int GetItemForgeDraftInt(const std::vector<std::pair<std::string, std::string>> &values, const std::string &key, const int fallback)
	{
		const auto value = GetItemForgeDraftValue(values, key);
		return value.empty() ? fallback : Strings::ToInt(value);
	}

	uint32 BuildSlotMask(const std::initializer_list<int> slots)
	{
		uint32 mask = 0;
		for (const auto slot : slots) {
			mask |= static_cast<uint32>(1u << slot);
		}

		return mask;
	}

	uint32 FindFreeForgedLiveItemID()
	{
		const auto minimum = static_cast<uint32>(std::max(1, RuleI(Items, LiveItemMinID)));
		const auto maximum = static_cast<uint32>(std::max(0, RuleI(Items, LiveItemMaxID)));

		auto start = static_cast<uint32>(Strings::ToUnsignedInt(DataBucket::GetData(&database, LiveItemForgeNextBucket)));
		if (start < minimum) {
			start = minimum;
		}

		for (uint32 item_id = start; item_id <= maximum || maximum == 0; ++item_id) {
			if (maximum && item_id > maximum) {
				break;
			}

			if (database.IsLiveItemID(item_id) && !ItemsRepository::FindOne(database, item_id).id) {
				DataBucket::SetData(&database, LiveItemForgeNextBucket, std::to_string(item_id + 1));
				return item_id;
			}

			if (maximum == 0 && item_id == std::numeric_limits<uint32>::max()) {
				break;
			}
		}

		return 0;
	}

	void ApplyItemForgeType(ItemsRepository::Items &item, const ItemForgeDefinition &definition)
	{
		const auto type = Strings::ToLower(definition.item_type);
		if (type == "augment" || type == "aug") {
			item.itemtype = EQ::item::ItemTypeAugmentation;
			item.slots = 0;
			item.icon = 646;
			item.augtype = 7;
			item.augslot1type = 0;
			item.augslot1visible = 0;
			item.augslot2type = 0;
			item.augslot2visible = 0;
			item.damage = 0;
			item.delay = 0;
			item.haste = 0;
			item.ac = std::max(item.ac, 3);
			return;
		}

		if (type == "armor") {
			item.itemtype = EQ::item::ItemTypeArmor;
			item.slots = BuildSlotMask({EQ::invslot::slotChest});
			item.icon = 538;
			item.damage = 0;
			item.delay = 0;
			item.haste = 0;
			item.ac = std::max(item.ac, 10);
			return;
		}

		if (type == "jewelry") {
			item.itemtype = EQ::item::ItemTypeJewelry;
			item.slots = BuildSlotMask({EQ::invslot::slotFinger1, EQ::invslot::slotFinger2});
			item.icon = 674;
			item.damage = 0;
			item.delay = 0;
			item.haste = 0;
			item.ac = std::max(0, item.ac / 2);
			return;
		}

		if (type == "charm") {
			item.itemtype = EQ::item::ItemTypeCharm;
			item.slots = BuildSlotMask({EQ::invslot::slotCharm});
			item.icon = 1123;
			item.damage = 0;
			item.delay = 0;
			item.haste = 0;
			return;
		}

		if (type == "shield") {
			item.itemtype = EQ::item::ItemTypeShield;
			item.slots = BuildSlotMask({EQ::invslot::slotSecondary});
			item.icon = 535;
			item.damage = 0;
			item.delay = 0;
			item.haste = 0;
			item.ac = std::max(item.ac, 15);
			return;
		}

		item.itemtype = EQ::item::ItemType1HSlash;
		item.slots = BuildSlotMask({EQ::invslot::slotPrimary, EQ::invslot::slotSecondary});
		item.icon = 519;
	}

	bool ApplyItemForgeNamedStat(ItemsRepository::Items &item, const std::string &raw_key, const int value)
	{
		const auto key = Strings::ToLower(raw_key);
		if (key == "str" || key == "astr") { item.astr = value; return true; }
		if (key == "sta" || key == "con" || key == "asta") { item.asta = value; return true; }
		if (key == "dex" || key == "adex") { item.adex = value; return true; }
		if (key == "agi" || key == "aagi") { item.aagi = value; return true; }
		if (key == "int" || key == "aint") { item.aint = value; return true; }
		if (key == "wis" || key == "awis") { item.awis = value; return true; }
		if (key == "cha" || key == "acha") { item.acha = value; return true; }
		if (key == "hp") { item.hp = value; return true; }
		if (key == "mana") { item.mana = value; return true; }
		if (key == "endur" || key == "endurance") { item.endur = value; return true; }
		if (key == "ac") { item.ac = value; return true; }
		if (key == "atk" || key == "attack") { item.attack = value; return true; }
		if (key == "accuracy") { item.accuracy = value; return true; }
		if (key == "avoidance") { item.avoidance = value; return true; }
		if (key == "regen") { item.regen = value; return true; }
		if (key == "manaregen") { item.manaregen = value; return true; }
		if (key == "enduranceregen" || key == "endregen") { item.enduranceregen = value; return true; }
		if (key == "haste") { item.haste = value; return true; }
		if (key == "damage") { item.damage = value; return true; }
		if (key == "delay") { item.delay = value; return true; }
		if (key == "mr") { item.mr = value; return true; }
		if (key == "fr") { item.fr = value; return true; }
		if (key == "cr") { item.cr = value; return true; }
		if (key == "pr") { item.pr = value; return true; }
		if (key == "dr") { item.dr = value; return true; }
		if (key == "svcorruption" || key == "corrup") { item.svcorruption = value; return true; }
		if (key == "shielding") { item.shielding = value; return true; }
		if (key == "spellshield") { item.spellshield = value; return true; }
		if (key == "dotshielding") { item.dotshielding = value; return true; }
		if (key == "stunresist") { item.stunresist = value; return true; }
		if (key == "strikethrough") { item.strikethrough = value; return true; }
		if (key == "damageshield") { item.damageshield = value; return true; }
		if (key == "dsmitigation") { item.dsmitigation = value; return true; }
		if (key == "healamt") { item.healamt = value; return true; }
		if (key == "spelldmg") { item.spelldmg = value; return true; }
		if (key == "clairvoyance") { item.clairvoyance = value; return true; }
		if (key == "backstabdmg") { item.backstabdmg = value; return true; }
		if (key == "heroic_str") { item.heroic_str = value; return true; }
		if (key == "heroic_sta" || key == "heroic_con") { item.heroic_sta = value; return true; }
		if (key == "heroic_dex") { item.heroic_dex = value; return true; }
		if (key == "heroic_agi") { item.heroic_agi = value; return true; }
		if (key == "heroic_int") { item.heroic_int = value; return true; }
		if (key == "heroic_wis") { item.heroic_wis = value; return true; }
		if (key == "heroic_cha") { item.heroic_cha = value; return true; }
		if (key == "heroic_mr") { item.heroic_mr = value; return true; }
		if (key == "heroic_fr") { item.heroic_fr = value; return true; }
		if (key == "heroic_cr") { item.heroic_cr = value; return true; }
		if (key == "heroic_pr") { item.heroic_pr = value; return true; }
		if (key == "heroic_dr") { item.heroic_dr = value; return true; }
		if (key == "heroic_svcorrup" || key == "heroic_corrup") { item.heroic_svcorrup = value; return true; }
		return false;
	}

	void ApplyItemForgeNamedStats(ItemsRepository::Items &item, const Seperator *sep)
	{
		for (int index = 2; index <= sep->argnum; ++index) {
			std::string key;
			std::string value;
			if (!ParseItemForgeToken(sep->arg[index], key, value)) {
				continue;
			}

			if (key.empty() || value.empty() || key == "name" || key == "type") {
				continue;
			}

			ApplyItemForgeNamedStat(item, key, Strings::ToInt(value));
		}
	}

	void ApplyItemForgeNamedStats(ItemsRepository::Items &item, const std::vector<std::pair<std::string, std::string>> &values)
	{
		for (const auto &[key, value] : values) {
			if (key.empty() || value.empty() || key == "name" || key == "type") {
				continue;
			}

			ApplyItemForgeNamedStat(item, key, Strings::ToInt(value));
		}
	}

	const char *ItemForgeStatPayload()
	{
		return "hp,mana,endur,ac,str,sta,dex,agi,int,wis,cha,mr,fr,cr,pr,dr,svcorruption,"
		       "attack,accuracy,avoidance,regen,manaregen,enduranceregen,haste,damage,delay,"
		       "shielding,spellshield,dotshielding,stunresist,strikethrough,damageshield,"
		       "dsmitigation,healamt,spelldmg,clairvoyance,backstabdmg,heroic_str,heroic_sta,"
		       "heroic_dex,heroic_agi,heroic_int,heroic_wis,heroic_cha,heroic_mr,heroic_fr,"
		       "heroic_cr,heroic_pr,heroic_dr,heroic_svcorrup";
	}

	bool CreateForgedLiveItem(Client *c, ItemForgeDefinition definition, const Seperator *sep = nullptr, const std::vector<std::pair<std::string, std::string>> *named_values = nullptr)
	{
		definition.item_id = FindFreeForgedLiveItemID();
		definition.name = DecodeItemForgeText(definition.name);
		if (definition.name.empty()) {
			definition.name = fmt::format("{}'s Forged", c->GetCleanName());
		}

		definition.item_type = Strings::ToLower(definition.item_type);
		definition.hp = std::clamp(definition.hp, 0, 500);
		definition.mana = std::clamp(definition.mana, 0, 500);
		definition.ac = std::clamp(definition.ac, 0, 100);
		definition.damage = std::clamp(definition.damage, 0, 100);
		definition.delay = std::clamp(definition.delay, 10, 60);
		definition.haste = std::clamp(definition.haste, 0, 50);

		if (!definition.item_id) {
			c->Message(Chat::White, "No free live item ID is available in the configured live item range.");
			return false;
		}

		auto item = ItemsRepository::NewEntity();
		item.id = static_cast<int32>(definition.item_id);
		item.minstatus = 0;
		item.Name = definition.name;
		item.lore = fmt::format("A custom item shaped for {}", c->GetCleanName());
		item.comment = fmt::format("Generated by #itemforge for character {}", c->CharacterID());
		item.itemclass = EQ::item::ItemClassCommon;
		item.classes = 65535;
		item.races = 65535;
		item.norent = 255;
		item.nodrop = 0;
		item.size = EQ::item::ItemSizeMedium;
		item.weight = 10;
		item.magic = 1;
		item.loregroup = 0;
		item.maxcharges = -1;
		item.hp = definition.hp;
		item.mana = definition.mana;
		item.ac = definition.ac;
		item.damage = definition.damage;
		item.delay = definition.delay;
		item.haste = definition.haste;
		item.price = 0;
		item.sellrate = 1.0f;
		item.tradeskills = 0;
		item.updated = std::time(nullptr);

		ApplyItemForgeType(item, definition);
		if (sep) {
			ApplyItemForgeNamedStats(item, sep);
		}
		if (named_values) {
			ApplyItemForgeNamedStats(item, *named_values);
		}

		ItemsRepository::InsertOne(database, item);
		if (!ItemsRepository::FindOne(database, definition.item_id).id) {
			c->Message(Chat::White, fmt::format("Failed to create forged item {}.", definition.item_id).c_str());
			return false;
		}

		database.ClearLiveItemCache(definition.item_id);
		SummonLiveItem(c, definition.item_id, 1);
		c->Message(
			Chat::White,
			fmt::format(
				"Created {} as live item {}.",
				item.Name,
				definition.item_id
			).c_str()
		);

		return true;
	}

	void SendItemForgeUsage(Client *c)
	{
		c->Message(Chat::White, "Usage: #itemforge dialog");
		c->Message(Chat::White, "Usage: #itemforge craft type=weapon name=Storm_Blade hp=50 mana=20 ac=5 damage=12 delay=24 haste=5 str=10 heroic_str=2");
		c->Message(Chat::White, "Usage: #itemforge draft type=weapon name=Storm_Blade; #itemforge set hp=50; #itemforge finish");
	}
}

void command_itemforge(Client *c, const Seperator *sep)
{
	if (!LiveItemsEnabled()) {
		c->Message(Chat::White, "Live Items are disabled on this server.");
		return;
	}

	const auto arguments = sep->argnum;
	if (!arguments || !strcasecmp(sep->arg[1], "help")) {
		SendItemForgeUsage(c);
		return;
	}

	const bool is_dialog = !strcasecmp(sep->arg[1], "dialog") || !strcasecmp(sep->arg[1], "open");
	const bool is_craft = !strcasecmp(sep->arg[1], "craft") || !strcasecmp(sep->arg[1], "create");
	const bool is_draft = !strcasecmp(sep->arg[1], "draft") || !strcasecmp(sep->arg[1], "begin");
	const bool is_set = !strcasecmp(sep->arg[1], "set");
	const bool is_finish = !strcasecmp(sep->arg[1], "finish");
	const bool is_reset = !strcasecmp(sep->arg[1], "reset");

	if (is_dialog) {
		c->Message(Chat::White, "Opening the Item Forge.");
		c->Message(
			Chat::White,
			fmt::format(
				"LIVEITEM|ui|open|types=weapon,armor,jewelry,charm,shield,augment|max_hp=500|max_mana=500|max_ac=100|max_damage=100|max_haste=50|stats={}",
				ItemForgeStatPayload()
			).c_str()
		);
		return;
	}

	if (is_draft) {
		auto values = ParseItemForgeDraft("");
		for (int index = 2; index <= sep->argnum; ++index) {
			std::string key;
			std::string value;
			if (ParseItemForgeToken(sep->arg[index], key, value)) {
				if (key == "name") {
					value = SanitizeItemForgeName(value);
				}
				SetItemForgeDraftValue(values, key, value);
			}
		}

		if (GetItemForgeDraftValue(values, "type").empty()) {
			SetItemForgeDraftValue(values, "type", "weapon");
		}

		if (GetItemForgeDraftValue(values, "name").empty()) {
			SetItemForgeDraftValue(values, "name", "Forged_Item");
		}

		DataBucket::SetData(&database, ItemForgeDraftBucketKey(c), BuildItemForgeDraft(values), "60");
		c->Message(Chat::White, "Item Forge draft started.");
		return;
	}

	if (is_set) {
		if (arguments < 2) {
			c->Message(Chat::White, "Usage: #itemforge set hp=50");
			return;
		}

		auto values = ParseItemForgeDraft(DataBucket::GetData(&database, ItemForgeDraftBucketKey(c)));
		if (values.empty()) {
			SetItemForgeDraftValue(values, "type", "weapon");
			SetItemForgeDraftValue(values, "name", "Forged_Item");
		}

		std::string key;
		std::string value;
		if (!ParseItemForgeToken(sep->arg[2], key, value)) {
			c->Message(Chat::White, "Usage: #itemforge set hp=50");
			return;
		}

		if (key == "name") {
			value = SanitizeItemForgeName(value);
		}

		SetItemForgeDraftValue(values, key, value);
		DataBucket::SetData(&database, ItemForgeDraftBucketKey(c), BuildItemForgeDraft(values), "60");
		return;
	}

	if (is_finish) {
		const auto draft_key = ItemForgeDraftBucketKey(c);
		auto values = ParseItemForgeDraft(DataBucket::GetData(&database, draft_key));
		if (values.empty()) {
			c->Message(Chat::White, "No Item Forge draft is active. Reopen the forge and try again.");
			return;
		}

		ItemForgeDefinition definition;
		const auto item_type = GetItemForgeDraftValue(values, "type");
		const auto name = GetItemForgeDraftValue(values, "name");
		if (!item_type.empty()) {
			definition.item_type = item_type;
		}

		if (!name.empty()) {
			definition.name = name;
		}

		definition.hp = GetItemForgeDraftInt(values, "hp", definition.hp);
		definition.mana = GetItemForgeDraftInt(values, "mana", definition.mana);
		definition.ac = GetItemForgeDraftInt(values, "ac", definition.ac);
		definition.damage = GetItemForgeDraftInt(values, "damage", definition.damage);
		definition.delay = GetItemForgeDraftInt(values, "delay", definition.delay);
		definition.haste = GetItemForgeDraftInt(values, "haste", definition.haste);

		CreateForgedLiveItem(c, definition, nullptr, &values);
		DataBucket::DeleteData(&database, draft_key);
		return;
	}

	if (is_reset) {
		DataBucket::DeleteData(&database, ItemForgeDraftBucketKey(c));
		c->Message(Chat::White, "Item Forge draft cleared.");
		return;
	}

	if (!is_craft) {
		SendItemForgeUsage(c);
		return;
	}

	ItemForgeDefinition definition;
	if (HasItemForgeNamedArgs(sep)) {
		const auto item_type = GetItemForgeNamedArg(sep, "type");
		const auto name = GetItemForgeNamedArg(sep, "name");
		if (!item_type.empty()) {
			definition.item_type = item_type;
		}

		if (!name.empty()) {
			definition.name = name;
		}

		definition.hp = GetItemForgeNamedInt(sep, "hp", definition.hp);
		definition.mana = GetItemForgeNamedInt(sep, "mana", definition.mana);
		definition.ac = GetItemForgeNamedInt(sep, "ac", definition.ac);
		definition.damage = GetItemForgeNamedInt(sep, "damage", definition.damage);
		definition.delay = GetItemForgeNamedInt(sep, "delay", definition.delay);
		definition.haste = GetItemForgeNamedInt(sep, "haste", definition.haste);
	} else {
		definition.item_type = arguments >= 2 ? std::string(sep->arg[2]) : definition.item_type;
		definition.hp = (arguments >= 3 && sep->IsNumber(3)) ? Strings::ToInt(sep->arg[3]) : definition.hp;
		definition.mana = (arguments >= 4 && sep->IsNumber(4)) ? Strings::ToInt(sep->arg[4]) : definition.mana;
		definition.ac = (arguments >= 5 && sep->IsNumber(5)) ? Strings::ToInt(sep->arg[5]) : definition.ac;
		definition.damage = (arguments >= 6 && sep->IsNumber(6)) ? Strings::ToInt(sep->arg[6]) : definition.damage;
		definition.delay = (arguments >= 7 && sep->IsNumber(7)) ? Strings::ToInt(sep->arg[7]) : definition.delay;
		definition.haste = (arguments >= 8 && sep->IsNumber(8)) ? Strings::ToInt(sep->arg[8]) : definition.haste;
	}

	CreateForgedLiveItem(c, definition, sep);
}

void command_liveitem(Client *c, const Seperator *sep)
{
	if (!LiveItemsEnabled()) {
		c->Message(Chat::White, "Live Items are disabled on this server.");
		return;
	}

	const auto arguments = sep->argnum;
	if (!arguments || !strcasecmp(sep->arg[1], "help")) {
		SendLiveItemUsage(c);
		return;
	}

	const bool is_status = !strcasecmp(sep->arg[1], "status");
	const bool is_clear  = !strcasecmp(sep->arg[1], "clear");
	const bool is_clone  = !strcasecmp(sep->arg[1], "clone");
	const bool is_summon = !strcasecmp(sep->arg[1], "summon");
	const bool is_bump   = !strcasecmp(sep->arg[1], "bump");

	if (!is_status && !is_clear && !is_clone && !is_summon && !is_bump) {
		SendLiveItemUsage(c);
		return;
	}

	if (is_clear) {
		if (arguments < 2 || !strcasecmp(sep->arg[2], "all")) {
			database.ClearLiveItemCache();
			c->Message(Chat::White, "Cleared all live item cache entries.");
			return;
		}

		if (!sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		c->Message(
			Chat::White,
			fmt::format(
				"Live item cache entry for item ID {} {}.",
				item_id,
				database.ClearLiveItemCache(item_id) ? "cleared" : "was not cached"
			).c_str()
		);
		return;
	}

	if (is_status) {
		if (arguments < 2 || !sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		const bool eligible = database.IsLiveItemID(item_id);
		c->Message(Chat::White, fmt::format("Live Item ID [{}]: {}", item_id, eligible ? "eligible" : "not eligible").c_str());

		const auto *item = database.GetItem(item_id);
		SendItemSummary(c, item);

		SharedDatabase::LiveItemCacheEntry entry {};
		if (database.GetLiveItemCacheEntry(item_id, entry)) {
			c->Message(
				Chat::White,
				fmt::format(
					"Cache: exists [{}] last_checked [{}] updated [{}]",
					entry.exists ? "true" : "false",
					entry.last_checked,
					entry.updated
				).c_str()
			);
		} else {
			c->Message(Chat::White, "Cache: no entry.");
		}
		return;
	}

	if (is_clone) {
		if (arguments < 3 || !sep->IsNumber(2) || !sep->IsNumber(3)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto target_id = Strings::ToUnsignedInt(sep->arg[2]);
		const auto source_id = Strings::ToUnsignedInt(sep->arg[3]);
		if (!IsValidLiveItemID(c, target_id) || !IsValidLiveItemID(c, source_id)) {
			return;
		}

		if (!database.IsLiveItemID(target_id)) {
			c->Message(Chat::White, fmt::format("Item ID {} is outside the configured live item range.", target_id).c_str());
			return;
		}

		if (UpsertLiveItemClone(c, target_id, source_id)) {
			SummonLiveItem(c, target_id, 1);
		}
		return;
	}

	if (is_summon) {
		if (arguments < 2 || !sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		const int16 charges = (arguments >= 3 && sep->IsNumber(3)) ? static_cast<int16>(Strings::ToInt(sep->arg[3])) : -1;
		SummonLiveItem(c, item_id, charges);
		return;
	}

	if (is_bump) {
		if (arguments < 2 || !sep->IsNumber(2)) {
			SendLiveItemUsage(c);
			return;
		}

		const auto item_id = Strings::ToUnsignedInt(sep->arg[2]);
		if (!IsValidLiveItemID(c, item_id)) {
			return;
		}

		if (!database.IsLiveItemID(item_id)) {
			c->Message(Chat::White, fmt::format("Item ID {} is outside the configured live item range.", item_id).c_str());
			return;
		}

		auto item = ItemsRepository::FindOne(database, item_id);
		if (!item.id) {
			c->Message(Chat::White, fmt::format("Item ID {} does not exist in the database.", item_id).c_str());
			return;
		}

		const int hp_step     = (arguments >= 3 && sep->IsNumber(3)) ? Strings::ToInt(sep->arg[3]) : 5;
		const int mana_step   = (arguments >= 4 && sep->IsNumber(4)) ? Strings::ToInt(sep->arg[4]) : 5;
		const int damage_step = (arguments >= 5 && sep->IsNumber(5)) ? Strings::ToInt(sep->arg[5]) : 1;

		item.hp = std::max(0, item.hp + hp_step);
		item.mana = std::max(0, item.mana + mana_step);
		item.damage = std::max(0, item.damage + damage_step);
		item.updated = std::time(nullptr);

		if (!ItemsRepository::UpdateOne(database, item)) {
			c->Message(Chat::White, fmt::format("Failed to bump item ID {}.", item_id).c_str());
			return;
		}

		c->Message(
			Chat::White,
			fmt::format(
				"Bumped item ID {} to HP [{}], Mana [{}], Damage [{}]. Wait up to the live item poll interval for held instances to refresh.",
				item_id,
				item.hp,
				item.mana,
				item.damage
			).c_str()
		);
	}
}
